### ISSUE TITLE
Comments for PhotoSift - by Stamimail

### ISSUE THREAD

**Issue by Stamimail** [rlv-dan/PhotoSift#2]
Bugs:
Win + Arrows   - shouldn't navigate, but just resize the window.
F4 - Should be located at menu. This feature (Enlarge image to fit window) was very missing to me at the previous time I'd tested this program, and then abandoned. IMO needs to be enabled at first run.
I encountered sometimes Errors when I did Ctrl+Z for Undo. I think the image file indeed was moved back but for some reason it says error. Anyway, I did not notice exactly when it occurs.

Portability:
I think F9 and F12 don't support properly Relative Paths yet (%PhotoSift%\..\..).

There are some keys I want them otherwise than the defaults. It would be better of course to have a full mouse and keyboard customization options, I'm sure it must be come at some point ,but for now you can make available at least the most common customization used by users:

RightClick on image = Context Menu
Wheel Scroll - Should Zoom, and the zoom should follow what under the cursor (important).
LeftClick = DoNothing \ NextImage \ Start|Pause Slideshow \ HandTool (in Zoom)
Double LeftClick = Full screen

F12 – Settings Dialog - Key Folders:
The size and location of this settings dialog box must be saved for the next time you press F12. I opened it again and again to set the Key Folders, and each time needed to resize again and again.
I recommend separate the Key Folders section from the other general settings, and put it by it own. Key Folders supposed to be used also as a Legend. So please make Key Folders Hide/Unhide by a Hotkey, and remember the size and location of it.
Jump to key: It will be nice if the user will be able to press a key (i.e. X) and the cursor will jump to the key Path (i.e. X path) for editing.
It would be nice if the whole list could be copied (to clipboard and then to Excel) for manipulate. For example, if the user moved the Target Base Folder (F9), he will probably like to change also the all Paths accordingly.

Important features I needed while testing:
Ctrl+C Ctrl+X = Copy/Move the current displayed image file (for copying/moving to other location in Explorer, for cases you need to do it just once)
Ctrl+V = Add images to ImagePool (Instead of dropping, you can do Crtl+C in Explorer and then Ctrl+V in PhotoSIft)
Open Location of file (Show in Explorer).
Clear – This command needs a Hotkey (Maybe Crtl+W like in Word), and Dialog Box to approve.
Write the Dimensions (weight height) of each pic and the speed of animation.
Voidimageviewer has a nice feature of controlling the animation rate (speed), to make it fast/slower.

For comparing tasks:
Ctrl + N = New instance (Blank)
Ctrl + D = Duplicate (Open the current ImagePool in a new instance)

Slideshow:
Gif's in Slideshow – an option to move to the next image at the end of the gif animation (if the animation length time is longer than the slideshow delay time). (Pics by seconds and Gifs by End of animation or Seconds)
Make ► indicator to see if slideshow is Played/Paused

Dropping Images:
Drop = should make a new session (a New ImagePool) in current window rather than add images to the end of the current image list.
Ctrl+Drop = add images to the end of the current image list.
Drop on TaskbarButton (Open WIth) - Open the dropped images in a new instance.

Navigate:
It's too common commands for putting it deep in Menu. Consider move the whole ImagePool commands to (under) File MenuItem and make Navigate as a parent MenuItem.
Add "Go to Next/Prev Folder" commands (When dropping a list of folders, so that you can skip to the next group (=folder) of pics Cars/Flowers/etc).
Home/End - The Navigation is stuck when arrived to the first/last image. It would be better to let it go (loop). You can also put a Blank screen in the middle when you got Home/End.

Summarize:
I found PhotoSift as a powerful tool for images organization. The side of "images organizer" is much developed than the "image viewer" side.
Since I was looking for an alternative to Windows Viewer (Image quality problem), I wish PhotoSift will keep develop the "image viewer" side. After all, PhotoSift doesn't need much to be a great "image viewer", and as an "image viewer" it will be more used (daily) rather than "images organizer" (seldom). You can simply do:
"Organizer mode" and "Viewer mode" to avoid the "Key Folders" Hotkeys available in Viewer mode.

On the other hand,

I wish PhotoSift will keep develop also the "images organizer" side.
This organizer program doesn't have to stop with photos. The same technique can be used very helpfully for all kinds of files.
You can use Windows Preview handlers for displaying them in the program.
It means PhotoSift will have "Photos mode" and "All Files mode".

Regards,
Stamimail

**Comment by Stamimail** [comment]
> Portability:
I think F9 and F12 don't support properly Relative Paths yet (%PhotoSift%....).

Maybe the solution is:
`<TargetFolder>.</TargetFolder>`
?

**Comment by Stamimail** [comment]
I tryed:
`<TargetFolder>.</TargetFolder>`

I don't know why,
But there is a different between:
1. Drag and Drop a folder on the EXE
2. Run the EXE and Drag and Drop a folder into the program window.

It seems the TargetFolder is not the same. I think it should be.

**Comment by yfdyh000** [comment]
@Stamimail If you still use this program, you may like my fork:
https://github.com/yfdyh000/PhotoSift/releases
Feedback is welcome.

**Comment by Stamimail** [comment]
@yfdyh000 I'm glad to here that.
I will need to find time for this.
The first question I will ask:
Does it have support for mp3, pdf and other file types?
What is your focus in developing :  the "File organizer" or the "Image viewer"?

**Comment by yfdyh000** [comment]
> @yfdyh000 I'm glad to here that.
> I will need to find time for this.
> The first question I will ask:
> Does it have support for mp3, pdf and other file types?
> What is your focus in developing : the "File organizer" or the "Image viewer"?

Audio and video playback has been developed, and you should be able to play it with the embedded Windows Media Player.

There are no plans for PDFs, I guess browse and sorting them may be too heavy in the view of the software. However, I have plans to support comic archives (such as zip), appreciate some comic browsers like MangaMeeya, and they support PDFs and many other formats through the AviSynth plugins & Susie Plug-ins, this is a direction that I am not familiar with but has a bright future.

The current direction is a media file organizer (manual classifier), not a browser (but it can) or editor.

**Comment by rlv-dan** [comment]
Closing this as it contains too many items in one to respond to. But I have gone though everything and added a lot to my backlog.

**Comment by Stamimail** [comment]
I will write here to address both of you @rlv-dan and @yfdyh000 

Consider to add Playlist panel like in Media Player

**Comment by yfdyh000** [comment]
> I will write here to address both of you @rlv-dan and @yfdyh000
> 
> Consider to add Playlist panel like in Media Player

I expect you to use something like xnview, developing a list or details is complicated and clumsy.

**Comment by Stamimail** [comment]
In case in your Playlist there some files you need to view/play in order to organize them, and some files you can organize them by their filenames.
I think a Playlist can help to select those files you can organize by filenames.

**Comment by yfdyh000** [comment]
> In case in your Playlist there some files you need to view/play in order to organize them, and some files you can organize them by their filenames.
> I think a Playlist can help to select those files you can organize by filenames.

Drag and drop to the software after selecting the files you want in the Explorer with Shift+click or Ctrl+Click, details view and sorting.
